webtalk_init -webtalk_dir C:/Users/shuos/Desktop/TRABAJO_SED/TRABAJO_SED.sim/sim_1/behav/xsim/xsim.dir/display_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 17 14:13:15 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8b95437f-9525-4e60-b627-e3c14bbfd074" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e95eb736a5324c7186e8c11d9e2694e7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "31400 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15276_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2554530613 -regid "" -xml C:/Users/shuos/Desktop/TRABAJO_SED/TRABAJO_SED.sim/sim_1/behav/xsim/xsim.dir/display_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/shuos/Desktop/TRABAJO_SED/TRABAJO_SED.sim/sim_1/behav/xsim/xsim.dir/display_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/shuos/Desktop/TRABAJO_SED/TRABAJO_SED.sim/sim_1/behav/xsim/xsim.dir/display_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
